version: '3.8'

services:
  ollama-mcp-server:
    build: .
    # Or use pre-built image:
    # image: docker.io/mup1987/ollama-mcp-server:latest
    environment:
      - OLLAMA_API=http://localhost:11434
    stdin_open: true
    tty: true
    restart: unless-stopped
    network_mode: host
    # Use host network to access localhost Ollama

  # Optional: Run Ollama in Docker too
  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   restart: unless-stopped

# volumes:
#   ollama_data:
#     driver: local
